

public class Account
{
	//talk to team about accountId which should be generated by the database
	public String dateCreated; 
	public User user;

	public Account(User user)
	{
		this.user = user;
	}
}